const SOVIL_CONTENT = {
  es: {
    nav: ['Qué hacemos', 'Proceso', 'Casos', 'Contacto'],
    hero: {
      eyebrow: 'Socio estratégico · Diseño, estrategia y ejecución',
      headline: 'Convertimos ideas en negocios digitales que funcionan.',
      sub: 'No desarrollamos por desarrollar. Construimos con criterio, acompañando cada decisión que importa.',
      cta: 'Agendar una llamada',
      ctaSecondary: 'Ver qué hacemos',
      microClaim: 'Las ideas sobran. Los negocios no.',
    },
    manifesto: {
      label: '01 · Qué somos',
      title: 'Un socio, no un proveedor.',
      body: 'SOVIL entra a ordenar, construir y escalar negocios usando tecnología como medio. No vendemos tecnología. Vendemos criterio, acompañamiento y ejecución real.',
      pillars: [
        { k: 'Criterio', v: 'Decisiones que impactan en el negocio, no features por inercia.' },
        { k: 'Acompañamiento', v: 'Estamos en cada paso, no desaparecemos después del kickoff.' },
        { k: 'Ejecución', v: 'Construimos lo que hay que construir. Cuando hay que construirlo.' },
      ],
    },
    services: {
      label: '02 · Qué hacemos',
      title: 'Cinco formas de hacer que las cosas funcionen.',
      items: [
        { n: '01', t: 'Bajamos ideas a modelos de negocio', d: 'Convertimos una intuición en algo concreto, medible y ejecutable.' },
        { n: '02', t: 'Diseñamos y desarrollamos soluciones digitales', d: 'Producto, plataforma, MVP. Lo que el negocio necesite.' },
        { n: '03', t: 'Acompañamos cada decisión clave', d: 'Estrategia, tech, producto, comercial. Entramos al detalle.' },
        { n: '04', t: 'Ordenamos proyectos que no funcionan', d: 'Diagnóstico honesto y plan para destrabar.' },
        { n: '05', t: 'Escalamos negocios que ya existen', d: 'Operación, producto y tech preparados para crecer.' },
      ],
    },
    triggers: {
      label: '03 · Cuándo entramos',
      title: 'Trabajamos cuando:',
      items: [
        'Hay una idea que no se logra ejecutar',
        'Un proyecto no está funcionando como debería',
        'Se necesita ordenar y estructurar',
        'Existe una oportunidad clara de escalar',
      ],
    },
    process: {
      label: '04 · Proceso',
      title: 'Cuatro etapas. Cero humo.',
      steps: [
        { n: '01', t: 'Diagnóstico', d: 'Entendemos el contexto real del negocio, el mercado y la gente. Sin presentaciones de relleno. Dos semanas, salida clara.' },
        { n: '02', t: 'Definición', d: 'Bajamos la idea a un modelo de negocio y una hoja de ruta de producto. Priorizamos por impacto.' },
        { n: '03', t: 'Construcción', d: 'Diseño y desarrollo en ciclos cortos. Cada entregable es usable, medible, defendible.' },
        { n: '04', t: 'Escala', d: 'Operación, métricas, iteración. Ajustamos lo que no funciona y multiplicamos lo que sí.' },
      ],
    },
    cases: {
      label: '05 · Casos',
      title: 'Negocios que hoy funcionan.',
      viewAll: 'Ver todos los casos',
      filters: ['Todos', 'Fintech', 'Retail', 'SaaS B2B'],
      items: [
        {
          sector: 'Fintech',
          client: 'Lendify',
          year: '2024',
          duration: '9 semanas',
          result: '+ 3x usuarios activos',
          brief: 'MVP de préstamos en 9 semanas. Arquitectura lista para escalar.',
          challenge: 'Una fintech early-stage necesitaba lanzar un MVP de préstamos personales antes de cerrar su ronda seed. Cero código, decisión de negocio sin validar y tres meses de runway.',
          approach: 'Diseñamos el producto de cero mapeando el customer journey en dos semanas. Paralelo a eso, armamos la arquitectura sobre AWS con foco en cumplimiento regulatorio. Pipeline de scoring crediticio integrado al core desde el día uno. Onboarding validado con 50 usuarios beta antes del lanzamiento público.',
          outcome: 'El MVP lanzó en 9 semanas. Triplicaron usuarios activos en el primer trimestre post-lanzamiento. Cerraron ronda seed 6 meses después con métricas reales, no proyecciones.',
          metrics: [
            { n: 9, s: 'sem', l: 'del idea a producción' },
            { n: 3, s: 'x', l: 'usuarios activos' },
            { n: 50, s: 'k', l: 'usd en la seed' },
            { n: 98, s: '%', l: 'uptime primer trimestre' },
          ],
          stack: ['React Native', 'Node.js', 'AWS', 'PostgreSQL', 'Redis', 'Stripe'],
          services: ['Product Strategy', 'UX/UI', 'Engineering', 'DevOps'],
          testimonial: {
            quote: 'No solo construyeron el producto. Nos obligaron a definir el negocio. Eso fue lo que cambió todo.',
            author: 'Mariana Suárez',
            role: 'CEO & Co-founder, Lendify',
          },
          images: ['Mobile onboarding', 'Credit score flow', 'Dashboard admin', 'API architecture'],
        },
        {
          sector: 'Retail',
          client: 'Nordia',
          year: '2023',
          duration: '14 semanas',
          result: '− 40% costo operativo',
          brief: 'Plataforma interna que ordenó 5 procesos dispersos.',
          challenge: 'Cadena de retail con 60 sucursales manejando inventario, compras, recursos humanos y logística en cinco sistemas distintos que no se hablaban entre sí. Errores operativos, datos desalineados y equipos perdiendo horas cargando información dos veces.',
          approach: 'Auditamos el mapa real de procesos durante tres semanas, entrevistando a 22 personas de cinco áreas. Diseñamos una plataforma unificada con módulos independientes pero con una única capa de datos. Migración progresiva, área por área, sin parar la operación. Capacitación en paralelo al desarrollo.',
          outcome: 'La plataforma reemplazó cinco sistemas legacy. Redujeron el costo operativo un 40% por consolidación de licencias y horas de equipo. Tiempo de consolidación de reportes de 3 días a 2 horas.',
          metrics: [
            { n: 40, s: '%', l: 'menos costo operativo' },
            { n: 5, s: '→1', l: 'sistemas consolidados' },
            { n: 60, s: '', l: 'sucursales conectadas' },
            { n: 22, s: 'h', l: 'ahorro semanal por sucursal' },
          ],
          stack: ['Next.js', 'TypeScript', 'Python', 'PostgreSQL', 'Docker', 'GCP'],
          services: ['Discovery', 'Product Design', 'Engineering', 'Change Management'],
          testimonial: {
            quote: 'Entendieron el negocio mejor que muchos consultores que tuvimos antes. Y después lo construyeron.',
            author: 'Federico Alonso',
            role: 'COO, Nordia Retail',
          },
          images: ['Dashboard principal', 'Módulo inventario', 'Reportería BI', 'Mobile app staff'],
        },
        {
          sector: 'SaaS B2B',
          client: 'Kairon',
          year: '2024',
          duration: '6 semanas',
          result: 'Pricing validado',
          brief: 'Redefinición de producto y go-to-market en 6 semanas.',
          challenge: 'SaaS B2B con producto técnicamente sólido pero con churn alto y ciclo de ventas impredecible. El equipo no sabía si el problema era precio, propuesta de valor o segmento mal elegido.',
          approach: 'Investigación con 40 clientes y ex-clientes en tres semanas. Redefinición de ICP con evidencia, no intuición. Pricing reestructurado en tres tiers alineados a valor percibido. Nuevo posicionamiento y GTM playbook para el equipo comercial.',
          outcome: 'El churn bajó 35% en el trimestre siguiente. Ticket promedio subió 60%. Ciclo de ventas se redujo de 47 a 28 días promedio.',
          metrics: [
            { n: 35, s: '%', l: 'menos churn' },
            { n: 60, s: '%', l: 'mayor ticket promedio' },
            { n: 28, s: 'd', l: 'ciclo de ventas' },
            { n: 40, s: '', l: 'entrevistas con clientes' },
          ],
          stack: ['Research', 'Mixpanel', 'Figma', 'Notion', 'HubSpot'],
          services: ['Product Discovery', 'Pricing Strategy', 'GTM Playbook'],
          testimonial: {
            quote: 'Vinieron a cuestionar todo. Nos incomodó. Seis semanas después, el negocio cambió.',
            author: 'Luciano Pérez',
            role: 'Founder & CEO, Kairon',
          },
          images: ['Customer research', 'Pricing deck', 'GTM playbook', 'Sales dashboard'],
        },
      ],
      placeholder: 'Casos reales disponibles bajo NDA',
      labels: {
        challenge: 'El desafío',
        approach: 'Nuestro abordaje',
        outcome: 'Resultados',
        metrics: 'Métricas clave',
        stack: 'Stack',
        services: 'Servicios',
        testimonial: 'Voz del cliente',
        gallery: 'Vistas del proyecto',
        duration: 'Duración',
        year: 'Año',
        client: 'Cliente',
        next: 'Siguiente caso',
        prev: 'Caso anterior',
        close: 'Cerrar',
        view: 'Ver caso completo',
      },
    },
    contact: {
      label: '06 · Contacto',
      title: 'Contanos qué querés destrabar.',
      sub: 'Respondemos en menos de 24h hábiles con una primera lectura honesta.',
      form: {
        name: 'Nombre',
        email: 'Email',
        company: 'Empresa',
        stage: '¿En qué etapa estás?',
        stages: ['Tengo una idea', 'Proyecto trabado', 'Quiero escalar', 'Todavía no sé'],
        message: 'Contanos un poco',
        messagePlaceholder: '¿Qué querés resolver? ¿Qué probaste? ¿Qué te trajo hasta acá?',
        submit: 'Agendar llamada',
        sending: 'Enviando…',
        sent: 'Listo. Te escribimos en menos de 24h.',
      },
    },
    footer: {
      tagline: 'Ideas en negocios digitales. Con criterio. Con acompañamiento.',
      rights: '© 2026 SOVIL. Todos los derechos reservados.',
      links: ['Privacidad', 'Términos', 'LinkedIn'],
    },
  },
  en: {
    nav: ['What we do', 'Process', 'Cases', 'Contact'],
    hero: {
      eyebrow: 'Strategic partner · Design, strategy and execution',
      headline: 'We turn ideas into digital businesses that actually work.',
      sub: "We don't build for the sake of building. We build with judgment, standing beside every decision that matters.",
      cta: 'Book a call',
      ctaSecondary: 'See what we do',
      microClaim: 'Ideas are everywhere. Businesses are not.',
    },
    manifesto: {
      label: '01 · Who we are',
      title: 'A partner, not a vendor.',
      body: "SOVIL comes in to order, build and scale businesses — using technology as the means. We don't sell tech. We sell judgment, partnership, and real execution.",
      pillars: [
        { k: 'Judgment', v: 'Decisions that move the business, not features out of inertia.' },
        { k: 'Partnership', v: "We're with you at every step. We don't vanish after kickoff." },
        { k: 'Execution', v: 'We build what needs to be built. When it needs to be built.' },
      ],
    },
    services: {
      label: '02 · What we do',
      title: 'Five ways to make things work.',
      items: [
        { n: '01', t: 'Turn ideas into business models', d: 'We take an intuition and make it concrete, measurable, executable.' },
        { n: '02', t: 'Design and build digital products', d: 'Product, platform, MVP. Whatever the business needs.' },
        { n: '03', t: 'Stand by every key decision', d: 'Strategy, tech, product, commercial. We get into the detail.' },
        { n: '04', t: "Fix projects that aren't working", d: 'Honest diagnosis and a plan to unblock.' },
        { n: '05', t: 'Scale businesses that already exist', d: 'Operations, product and tech ready to grow.' },
      ],
    },
    triggers: {
      label: '03 · When we step in',
      title: 'We work when:',
      items: [
        "There's an idea that can't get executed",
        "A project isn't working the way it should",
        'Things need to be ordered and structured',
        "There's a clear opportunity to scale",
      ],
    },
    process: {
      label: '04 · Process',
      title: 'Four stages. Zero fluff.',
      steps: [
        { n: '01', t: 'Diagnosis', d: 'We understand the real context — business, market, people. No filler decks. Two weeks, clear output.' },
        { n: '02', t: 'Definition', d: 'We turn the idea into a business model and a product roadmap. Prioritized by impact.' },
        { n: '03', t: 'Build', d: 'Design and development in short cycles. Every deliverable is usable, measurable, defensible.' },
        { n: '04', t: 'Scale', d: "Operations, metrics, iteration. We fix what doesn't work and multiply what does." },
      ],
    },
    cases: {
      label: '05 · Cases',
      title: 'Businesses that now work.',
      viewAll: 'View all cases',
      filters: ['All', 'Fintech', 'Retail', 'B2B SaaS'],
      items: [
        {
          sector: 'Fintech',
          client: 'Lendify',
          year: '2024',
          duration: '9 weeks',
          result: '+ 3x active users',
          brief: 'Lending MVP in 9 weeks. Architecture ready to scale.',
          challenge: 'An early-stage fintech needed to launch a personal-lending MVP before closing their seed round. No code yet, unvalidated business bet, three months of runway.',
          approach: 'We designed the product from zero, mapping the customer journey in two weeks. In parallel we built the architecture on AWS with regulatory compliance baked in. A credit-scoring pipeline integrated from day one. Onboarding validated with 50 beta users before public launch.',
          outcome: 'The MVP shipped in 9 weeks. Active users tripled in the first quarter post-launch. They closed the seed round 6 months later on real metrics, not projections.',
          metrics: [
            { n: 9, s: 'w', l: 'from idea to production' },
            { n: 3, s: 'x', l: 'active users' },
            { n: 50, s: 'k', l: 'usd seed round' },
            { n: 98, s: '%', l: 'uptime first quarter' },
          ],
          stack: ['React Native', 'Node.js', 'AWS', 'PostgreSQL', 'Redis', 'Stripe'],
          services: ['Product Strategy', 'UX/UI', 'Engineering', 'DevOps'],
          testimonial: {
            quote: "They didn't just build the product. They forced us to define the business. That changed everything.",
            author: 'Mariana Suárez',
            role: 'CEO & Co-founder, Lendify',
          },
          images: ['Mobile onboarding', 'Credit score flow', 'Admin dashboard', 'API architecture'],
        },
        {
          sector: 'Retail',
          client: 'Nordia',
          year: '2023',
          duration: '14 weeks',
          result: '− 40% operating cost',
          brief: 'Internal platform that reordered 5 scattered processes.',
          challenge: 'A retail chain with 60 stores running inventory, purchasing, HR and logistics across five disconnected systems. Operational errors, misaligned data, and teams re-entering information twice.',
          approach: 'We audited the real process map over three weeks, interviewing 22 people across five areas. Designed a unified platform with independent modules but a single data layer. Progressive migration, area by area, without pausing operations. Training ran in parallel with development.',
          outcome: 'The platform replaced five legacy systems. Operating cost dropped 40% from license consolidation and reclaimed team hours. Reporting time went from 3 days to 2 hours.',
          metrics: [
            { n: 40, s: '%', l: 'lower operating cost' },
            { n: 5, s: '→1', l: 'systems consolidated' },
            { n: 60, s: '', l: 'stores connected' },
            { n: 22, s: 'h', l: 'weekly saving per store' },
          ],
          stack: ['Next.js', 'TypeScript', 'Python', 'PostgreSQL', 'Docker', 'GCP'],
          services: ['Discovery', 'Product Design', 'Engineering', 'Change Management'],
          testimonial: {
            quote: 'They understood the business better than most consultants we hired before. And then they built it.',
            author: 'Federico Alonso',
            role: 'COO, Nordia Retail',
          },
          images: ['Main dashboard', 'Inventory module', 'BI reporting', 'Mobile staff app'],
        },
        {
          sector: 'B2B SaaS',
          client: 'Kairon',
          year: '2024',
          duration: '6 weeks',
          result: 'Pricing validated',
          brief: 'Product and go-to-market redefinition in 6 weeks.',
          challenge: "A technically solid B2B SaaS with high churn and an unpredictable sales cycle. The team couldn't tell if the problem was price, value prop, or the wrong segment.",
          approach: 'Research with 40 current and former customers in three weeks. ICP redefined on evidence, not intuition. Pricing restructured into three tiers aligned with perceived value. New positioning and a GTM playbook for the sales team.',
          outcome: 'Churn dropped 35% the following quarter. Average ticket rose 60%. Sales cycle shortened from 47 to 28 days.',
          metrics: [
            { n: 35, s: '%', l: 'less churn' },
            { n: 60, s: '%', l: 'higher avg. ticket' },
            { n: 28, s: 'd', l: 'sales cycle' },
            { n: 40, s: '', l: 'customer interviews' },
          ],
          stack: ['Research', 'Mixpanel', 'Figma', 'Notion', 'HubSpot'],
          services: ['Product Discovery', 'Pricing Strategy', 'GTM Playbook'],
          testimonial: {
            quote: 'They came in and questioned everything. It made us uncomfortable. Six weeks later, the business had changed.',
            author: 'Luciano Pérez',
            role: 'Founder & CEO, Kairon',
          },
          images: ['Customer research', 'Pricing deck', 'GTM playbook', 'Sales dashboard'],
        },
      ],
      placeholder: 'Real cases available under NDA',
      labels: {
        challenge: 'The challenge',
        approach: 'Our approach',
        outcome: 'Outcome',
        metrics: 'Key metrics',
        stack: 'Stack',
        services: 'Services',
        testimonial: 'Client voice',
        gallery: 'Project views',
        duration: 'Duration',
        year: 'Year',
        client: 'Client',
        next: 'Next case',
        prev: 'Previous case',
        close: 'Close',
        view: 'View full case',
      },
    },
    contact: {
      label: '06 · Contact',
      title: 'Tell us what you want to unblock.',
      sub: 'We reply in under 24 business hours with an honest first read.',
      form: {
        name: 'Name',
        email: 'Email',
        company: 'Company',
        stage: 'What stage are you at?',
        stages: ['I have an idea', 'Project stuck', 'I want to scale', "I don't know yet"],
        message: 'Tell us a bit',
        messagePlaceholder: 'What are you trying to solve? What have you tried? What brought you here?',
        submit: 'Book a call',
        sending: 'Sending…',
        sent: "Got it. We'll reach out within 24h.",
      },
    },
    footer: {
      tagline: 'Ideas into digital businesses. With judgment. With partnership.',
      rights: '© 2026 SOVIL. All rights reserved.',
      links: ['Privacy', 'Terms', 'LinkedIn'],
    },
  },
};

export default SOVIL_CONTENT;
